FROM ubuntu:20.04
MAINTAINER docker@ekito.fr

RUN apt-get update && apt-get -y install cron 

COPY dev/crontab /etc/cron.d/script-cron

RUN chmod 0755 /etc/cron.d/script-cron
RUN crontab /etc/cron.d/script-cron
RUN touch /var/log/cron.log

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install postgresql libpq-dev python3 python3-pip

WORKDIR /app

COPY ./requirements.txt /app

RUN pip3 install -r requirements.txt
 
CMD cron && tail -f /var/log/cron.log
