"""empty message

Revision ID: 17de7a1bad16
Revises: bbf13d065442
Create Date: 2023-04-21 00:18:06.044764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17de7a1bad16'
down_revision = 'bbf13d065442'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('email_list', sa.Column('source', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_email_list_source'), 'email_list', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_list_source'), table_name='email_list')
    op.drop_column('email_list', 'source')
    # ### end Alembic commands ###
