"""empty message

Revision ID: 192c21e69c4b
Revises: fd8a24ffff30
Create Date: 2019-04-08 22:52:25.066158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192c21e69c4b'
down_revision = 'fd8a24ffff30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_contact', sa.Column('investor_airdrop', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eth_contact', 'investor_airdrop')
    # ### end Alembic commands ###
