"""empty message

Revision ID: 241461fb2314
Revises: 3fae31bbf999
Create Date: 2022-08-03 19:41:17.900433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '241461fb2314'
down_revision = '3fae31bbf999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circulating_ogn_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_amount', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circulating_ogv_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_amount', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_circulating_supply_snapshot_date', table_name='circulating_supply')
    op.drop_table('circulating_supply')
    op.add_column('eth_contact', sa.Column('ogv_balance', sa.Float(), nullable=True))
    op.drop_index('ix_token_info_created_at', table_name='token_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_token_info_created_at', 'token_info', ['created_at'], unique=False)
    op.drop_column('eth_contact', 'ogv_balance')
    op.create_table('circulating_supply',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('supply_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='circulating_supply_pkey')
    )
    op.create_index('ix_circulating_supply_snapshot_date', 'circulating_supply', ['snapshot_date'], unique=False)
    op.drop_table('circulating_ogv_supply')
    op.drop_table('circulating_ogn_supply')
    # ### end Alembic commands ###
