"""empty message

Revision ID: 2892244b88e2
Revises: 2627b59a3f8b
Create Date: 2018-03-07 16:46:57.269523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2892244b88e2'
down_revision = '2627b59a3f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investorrating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('dollar_days_held', sa.Float(), nullable=True),
    sa.Column('maximum_dollar_days', sa.Float(), nullable=True),
    sa.Column('holding_ratio', sa.Float(), nullable=True),
    sa.Column('eth_balance', sa.Float(), nullable=True),
    sa.Column('token_usd_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investorrating_address'), 'investorrating', ['address'], unique=True)
    op.create_index(op.f('ix_investorrating_currency'), 'investorrating', ['currency'], unique=False)
    op.add_column(u'email_list', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    op.add_column(u'presale', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'presale', 'ip_addr')
    op.drop_column(u'email_list', 'ip_addr')
    op.drop_index(op.f('ix_investorrating_currency'), table_name='investorrating')
    op.drop_index(op.f('ix_investorrating_address'), table_name='investorrating')
    op.drop_table('investorrating')
    # ### end Alembic commands ###
