"""empty message

Revision ID: 2bb87569e701
Revises: 7f2cc42f04f6
Create Date: 2018-08-18 17:47:31.068689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb87569e701'
down_revision = '7f2cc42f04f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('username', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contributor')
    # ### end Alembic commands ###
