"""add ip_addr column

Revision ID: 353ae4db3695
Revises: 80a54752ff01
Create Date: 2018-02-17 03:01:59.381491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353ae4db3695'
down_revision = '80a54752ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest', 'ip_addr')
    # ### end Alembic commands ###
