"""empty message

Revision ID: 3fae31bbf999
Revises: c3ed0d58d753
Create Date: 2020-08-10 09:00:09.893849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fae31bbf999'
down_revision = 'c3ed0d58d753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holders', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('transfers_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_info_created_at'), 'token_info', ['created_at'], unique=False)
	# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_info_created_at'), table_name='token_info')
    op.drop_table('token_info')
    # ### end Alembic commands ###
