"""empty message

Revision ID: 43ca8f0e4e15
Revises: 59a1a430b7a6
Create Date: 2018-11-16 19:22:03.782468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ca8f0e4e15'
down_revision = '59a1a430b7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platform',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('selector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('json', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=u'social_platform_pkey')
    )
    # ### end Alembic commands ###
