"""empty message

Revision ID: 50be9a6a7f7a
Revises: 24e593efdb89
Create Date: 2020-02-07 19:22:25.204855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50be9a6a7f7a'
down_revision = '24e593efdb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_list', sa.Column('spam_report', sa.Boolean(), nullable=True))
    op.drop_column('email_list', 'reported_spam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_list', sa.Column('reported_spam', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('email_list', 'spam_report')
    # ### end Alembic commands ###
