"""empty message

Revision ID: 59a1a430b7a6
Revises: a070cfc2f066
Create Date: 2018-11-15 18:25:22.756626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a1a430b7a6'
down_revision = 'a070cfc2f066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('subscribed_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_stat_name'), 'social_stat', ['name'], unique=False)
    op.drop_column(u'social_platform', 'subscribed_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'social_platform', sa.Column('subscribed_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_social_stat_name'), table_name='social_stat')
    op.drop_table('social_stat')
    # ### end Alembic commands ###
