"""empty message

Revision ID: 618ce1079e81
Revises: da339822d5f9
Create Date: 2020-01-01 00:23:01.224227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618ce1079e81'
down_revision = 'da339822d5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_list', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('email_list', sa.Column('last_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_list', 'last_name')
    op.drop_column('email_list', 'first_name')
    # ### end Alembic commands ###
