"""empty message

Revision ID: 7349e38572bb
Revises: a3b829d089f2
Create Date: 2019-04-08 16:50:53.151261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7349e38572bb'
down_revision = 'a3b829d089f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_contact', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eth_contact', 'desc')
    # ### end Alembic commands ###
