"""empty message

Revision ID: 75a6937030ba
Revises: 353ae4db3695
Create Date: 2018-03-02 18:40:21.442635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a6937030ba'
down_revision = '353ae4db3695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_list', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    op.add_column('presale', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presale', 'ip_addr')
    op.drop_column('email_list', 'ip_addr')
    # ### end Alembic commands ###
