"""empty message

Revision ID: 77799c791f03
Revises: 
Create Date: 2018-01-30 14:11:55.771532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77799c791f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_list',
    sa.Column('email', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('msg_purpose', sa.String(length=128), nullable=True),
    sa.Column('msg_subject', sa.String(length=128), nullable=True),
    sa.Column('msg_text', sa.Text(), nullable=True),
    sa.Column('msg_html', sa.Text(), nullable=True),
    sa.Column('msg_sent', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_email'), 'message_log', ['email'], unique=False)
    op.create_index(op.f('ix_message_log_msg_purpose'), 'message_log', ['msg_purpose'], unique=False)
    op.create_table('presale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('accredited', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(length=255), nullable=True),
    sa.Column('desired_allocation', sa.String(length=255), nullable=True),
    sa.Column('desired_allocation_currency', sa.String(length=3), nullable=True),
    sa.Column('citizenship', sa.String(length=2), nullable=True),
    sa.Column('sending_addr', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presale')
    op.drop_index(op.f('ix_message_log_msg_purpose'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_email'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_table('interest')
    op.drop_table('email_list')
    # ### end Alembic commands ###
