"""empty message

Revision ID: 80a54752ff01
Revises: 77799c791f03
Create Date: 2018-02-13 16:18:53.645235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a54752ff01'
down_revision = '77799c791f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_list', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('interest', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    op.create_index(op.f('ix_message_log_email'), 'message_log', ['email'], unique=False)
    op.create_index(op.f('ix_message_log_msg_purpose'), 'message_log', ['msg_purpose'], unique=False)
    op.add_column('presale', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presale', 'created_at')
    op.drop_index(op.f('ix_message_log_msg_purpose'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_email'), table_name='message_log')
    op.drop_column('interest', 'created_at')
    op.drop_column('email_list', 'created_at')
    # ### end Alembic commands ###
