"""empty message

Revision ID: a0097ab973d5
Revises: 43ca8f0e4e15
Create Date: 2018-12-17 12:31:42.872790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0097ab973d5'
down_revision = '43ca8f0e4e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_credentials',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_youtube_credentials_refresh_token'), 'youtube_credentials', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_youtube_credentials_token'), 'youtube_credentials', ['token'], unique=False)
    op.create_index(op.f('ix_youtube_credentials_token_uri'), 'youtube_credentials', ['token_uri'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_credentials_token_uri'), table_name='youtube_credentials')
    op.drop_index(op.f('ix_youtube_credentials_token'), table_name='youtube_credentials')
    op.drop_index(op.f('ix_youtube_credentials_refresh_token'), table_name='youtube_credentials')
    op.drop_table('youtube_credentials')
    # ### end Alembic commands ###
