"""empty message

Revision ID: a070cfc2f066
Revises: a7ec73f3bc39
Create Date: 2018-11-05 12:50:37.514868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a070cfc2f066'
down_revision = 'a7ec73f3bc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_platform', sa.Column('json', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_platform', 'json')
    # ### end Alembic commands ###
