"""empty message

Revision ID: a3b829d089f2
Revises: 150566d7f57d
Create Date: 2019-04-08 16:34:09.549923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b829d089f2'
down_revision = '150566d7f57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_transaction', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_transaction', 'notification_sent')
    # ### end Alembic commands ###
