"""empty message

Revision ID: a7ec73f3bc39
Revises: 2bb87569e701
Create Date: 2018-10-30 12:36:27.241436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ec73f3bc39'
down_revision = '2bb87569e701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platform',
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('selector', sa.String(length=255), nullable=True),
    sa.Column('subscribed_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_platform')
    # ### end Alembic commands ###
