"""empty message

Revision ID: bbf13d065442
Revises: 3fae31bbf999
Create Date: 2022-08-04 13:32:29.859446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf13d065442'
down_revision = '3fae31bbf999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circulating_ogv_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_amount', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.rename_table('circulating_supply', 'circulating_ogn_supply')
    op.add_column('eth_contact', sa.Column('ogv_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eth_contact', 'ogv_balance')
    op.rename_table('circulating_ogn_supply', 'circulating_supply')
    op.drop_table('circulating_ogv_supply')
    # ### end Alembic commands ###
