"""empty message

Revision ID: cd2a8a7254ab
Revises: 2627b59a3f8b
Create Date: 2018-03-09 13:13:14.212337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2a8a7254ab'
down_revision = '2627b59a3f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('dollar_days_held', sa.Float(), nullable=True),
    sa.Column('maximum_dollar_days', sa.Float(), nullable=True),
    sa.Column('holding_ratio', sa.Float(), nullable=True),
    sa.Column('eth_balance', sa.Float(), nullable=True),
    sa.Column('token_usd_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_analytics_address'), 'address_analytics', ['address'], unique=True)
    op.create_index(op.f('ix_address_analytics_currency'), 'address_analytics', ['currency'], unique=False)
    op.add_column(u'email_list', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    op.add_column(u'presale', sa.Column('ip_addr', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'presale', 'ip_addr')
    op.drop_column(u'email_list', 'ip_addr')
    op.drop_index(op.f('ix_address_analytics_currency'), table_name='address_analytics')
    op.drop_index(op.f('ix_address_analytics_address'), table_name='address_analytics')
    op.drop_table('address_analytics')
    # ### end Alembic commands ###
