"""empty message

Revision ID: dc4ab410b290
Revises: a0097ab973d5
Create Date: 2019-02-05 08:43:25.885523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4ab410b290'
down_revision = 'a0097ab973d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_youtube_credentials_refresh_token', table_name='youtube_credentials')
    op.drop_index('ix_youtube_credentials_token', table_name='youtube_credentials')
    op.drop_index('ix_youtube_credentials_token_uri', table_name='youtube_credentials')
    op.drop_table('youtube_credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_credentials',
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token', name=u'youtube_credentials_pkey')
    )
    op.create_index('ix_youtube_credentials_token_uri', 'youtube_credentials', ['token_uri'], unique=False)
    op.create_index('ix_youtube_credentials_token', 'youtube_credentials', ['token'], unique=False)
    op.create_index('ix_youtube_credentials_refresh_token', 'youtube_credentials', ['refresh_token'], unique=False)
    # ### end Alembic commands ###
