"""empty message

Revision ID: e9a7b25e3c62
Revises: 192c21e69c4b
Create Date: 2019-04-09 11:12:55.546454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9a7b25e3c62'
down_revision = '192c21e69c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_contact', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('eth_contact', sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('eth_contact', sa.Column('transaction_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eth_contact', 'transaction_count')
    op.drop_column('eth_contact', 'tokens')
    op.drop_column('eth_contact', 'token_count')
    # ### end Alembic commands ###
