"""empty message

Revision ID: fd8a24ffff30
Revises: 7349e38572bb
Create Date: 2019-04-08 22:50:03.007521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8a24ffff30'
down_revision = '7349e38572bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_contact', sa.Column('phone', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_eth_contact_phone'), 'eth_contact', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eth_contact_phone'), table_name='eth_contact')
    op.drop_column('eth_contact', 'phone')
    # ### end Alembic commands ###
